site_name: Roact Documentation
repo_name: Roblox/roact
repo_url: https://github.com/Roblox/roact

theme:
  name: material
  palette:
    primary: 'Light Blue'
    accent: 'Light Blue'

pages:
  - Home: index.md
  - Getting Started: getting-started.md
  - Concepts:
    - Elements: concepts/elements.md
    - Elements and Components: concepts/elements-components.md
    - Props and State: concepts/props-and-state.md
    - Lifecycle of Components: concepts/lifecycle.md
    - Usage with Rodux: concepts/usage-with-rodux.md
  - Examples:
    - Hello, Roact!: examples/hello-roact.md
    - Stateful Counter: examples/counter.md
    - Events, the Roact Way: examples/events.md
    - Tearing Down Components: examples/teardown.md
    - Refs: examples/refs.md
    - Roact with Rodux: examples/roact-rodux.md
  - API Reference: api-reference.md

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true