site_name: Roact Documentation
repo_name: Roblox/roact
repo_url: https://github.com/Roblox/roact

theme:
  name: material
  palette:
    primary: 'Light Blue'
    accent: 'Light Blue'

pages:
  - Home: index.md
  - Guide:
    - Installation: guide/installation.md
    - Hello, Roact!: guide/hello-roact.md
    - Elements: guide/elements.md
  - Examples:
    - Stateful Counter: examples/counter.md
    - Events, the Roact Way: examples/events.md
    - Tearing Down Components: examples/teardown.md
    - Refs: examples/refs.md
    - Roact with Rodux: examples/roact-rodux.md
  - API Reference: api-reference.md

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true